name: Send Email on Push

on:
  push:
    branches: [any] # This sends email on push to any branch (replace with specific branches if needed)

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/email@v3
        with:
          subject: "Push Notification - ${{ github.sha }}"
          recipient: "your_email@example.com" # Replace with your email address
          body: |
            A push has been made to the repository.

            **Branch:** ${{ github.ref }}
            **SHA:** ${{ github.sha }}

            [View commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})  # Link to the commit
